% Description: update egoCar signals
% Author :                     
% log:
%****************************************************************% 
function mbdUpdateEgo(...
    speed, ...
    vx, ...
    vy, ...
    ax, ...
    ay, ...
    yawrate, ...
    SW_angle, ...
    SW_alpha, ...
    BPP, ...
    APP, ...
    wiper, ...
    indicator...
    )    %#codegen
% 更新用于车道线相关算法的车辆运行信息

global g_ego_status; %g_tracks_lane;
b_vy = vy;

% speed = km/h->m/s
if speed > 0 && vx == 0 && vy == 0
    b_vx = speed / 3.6;   
else
    b_vx = vx;
end

% 车道线拼接使用，兼顾
% if yawrate == 0
%     yawrate = g_tracks_lane.yawrate;
% else
% yawrate =  rad2deg(yawrate); % input:rad/s->deg/s

% end

g_ego_status = update_ego(g_ego_status, speed, b_vx, b_vy, ax, ay, yawrate, ...
    SW_angle, SW_alpha, BPP, APP, wiper, indicator);

end

