function disp_ego_params()    %#codegen
% Description: 显示车辆基本信息（全局变量）
% Author :  Shane Liu
% Modify Note: 
% ************************************************************ % 
global g_ego_params

s = sprintf(['-------- Vehicle Parameters ... --------\n' ...
    'Number of Axles\t: %u\n' ...
    'Width of Body\t: %.3fm\n' ...
    'Length of Body\t: %.3fm\n', ...
    'Height of Body\t: %.3fm\n', ...
    'Front Overhang\t: %.3fm\n', ...
    'Front WheelBase\t: %.3fm\n', ...
    'Axle 1 - 2 Base\t: %.3fm\n', ...
    'Axle 2 - 3 Base\t: %.3fm\n', ...
    'Axle 3 - 4 Base\t: %.3fm\n', ...
    'Curb Mass\t\t: %.0fKg\n', ...
    'Total Mass\t\t: %.0fKg\n', ...
    'Axle1 Weight\t: %.0fKg\n', ...
    'Axle2 Weight\t: %.0fKg\n', ...
    'Axle3 Weight\t: %.0fKg\n', ...
    'Axle4 Weight\t: %.0fKg\n', ...
    '-------- Vehicle Parameters end --------\n'], ...
    g_ego_params.axle_nums, g_ego_params.width, g_ego_params.length, ...
    g_ego_params.height, g_ego_params.front_overhang, ...
    g_ego_params.front_wheelbase, g_ego_params.axle12_base, ...
    g_ego_params.axle23_base, g_ego_params.axle34_base, ...
    g_ego_params.curb_mass, g_ego_params.total_mass, ...
    g_ego_params.axle1_weight, g_ego_params.axle2_weight, ...
    g_ego_params.axle3_weight, g_ego_params.axle4_weight ...
);
disp_info(s, info_cls.general)

end

