classdef lane_const
% Description: 车道线信息
% Author :  Shane Liu
% Modify Note: 
% ************************************************************ % 
    properties (Constant)
        max_lns = uint8(8);         % 单帧识别车道线最大数量（聚类数量）
        track_depth = uint8(6);   	% 车道线跟踪深度
        track_width = uint8(16);   	% 车道线跟踪数量
        defNominalErr = 1e4;        % 名义距离默认值
        maxNominalErr = 1;
        max_lane_num = uint8(4);

        % 车道线后处理参数
        cfg = struct(...
            'FPS', 15,...                   % 检测帧率
            'deltaT', 1/15,...              % 检测时间间隔
            'min_conf', 0.1,...             % 最低置信度，范围：0-1
            'x_coverage', [0, 150],...      % 纵向有效范围，单位：m
            'y_coverage', [-8, 8],...       % 横向有效范围，单位：m
            'w_coverage', [2.6, 4.9],...    % 车道宽度有效范围，单位：m
            'min_x_len', 20,...             % 纵向最短距离，单位：m
            'max_x_near', 15,...            % 车道线近端最远距离，单位：m
            'limit_x_near',10,...           % 车道线近端起始限制；单位：m
            'max_heading', 30,...           % 车道线相对于车身航向角绝对值上限，单位：弧度。车道线方程的abs(C1)大于此值时不予输出
            'min_radius', 150,...           % 车道线最小曲率半径，单位：m。车道线方程的abs(2*C2)小于此值时不予输出
            'def_wid_half', 1.8...         % 半车道宽度，单位：m
            );

         LaneXY = struct( ...
            'lane_locaiotn',lane_index.others,...  % 0:右车道 1:左车道
            'quality',lane_quality.other,...       % 0,1: low quality 2,3: high quality
            'lane_type', lane_cls.unknown,...     % 0: dashed 1: solid
            'width_marking',0,...
            'C0',0,...
            'C1',0,...
            'C2',0,...
            'C3',0,...
            'view_range',0,...
            'view_range_valid',uint8(0),...
            'flag',uint8(0) ...      %数据是否有效
            )
     
%         % 世界坐标系车道线输出值（解析式）
%         EO = struct(...
%             'ID', uint8(0),...
%             'C', [0 0 0 0],...
%             'range', [0 0],...
%             'index', lane_index.others,...
%             'cls', lane_cls.unknown,...
%             'conf',0,...
%             'width',0,...     % unit:cm
%             'state', track_status.untracking,...
%             'color',uint8(0), ...
%             'driv_area', uint8(0) ...
%             );
      
    end

end

